services:
  app:
    build: .
    container_name: atendente-virtual-ccim
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE_NAME=${EVOLUTION_INSTANCE_NAME}
      - DB_HOST=172.17.0.1
      - DB_DATABASE=automacaobeta
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_PORT=3306
    networks:
      - rede_geral

networks:
  rede_geral:
    external: true
