services:
  app:
    build: .
    container_name: agente-virtual-ccim-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - EVOLUTION_API_URL=http://127.0.0.1:8080
      - EVOLUTION_API_HASH=
      - EVOLUTION_INSTANCE_NAME=
      - EVOLUTION_API_KEY=
      - CORS_ORIGIN=*
      - WEBHOOK_URL=http://localhost:3000/webhook/whatsapp
      - DB_HOST=127.0.0.1
      - DB_DATABASE=app_db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_PORT=3306
    networks:
      - rede_geral

networks:
  rede_geral:
    external: true
