services:
  app:
    build: .
    container_name: agente-virtual-ccim-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - EVOLUTION_API_URL=http://127.0.0.1:8083
      - EVOLUTION_API_HASH=B2EE0C67A4D1-4FF7-8B53-7D47EEF00258
      - EVOLUTION_INSTANCE_NAME=Bruno2
      - EVOLUTION_API_KEY=123
      - CORS_ORIGIN=*
      - WEBHOOK_URL=https://bot.ccim.com.br/webhook/whatsapp
      - DB_HOST=127.0.0.1
      - DB_DATABASE=bot-ccm
      - DB_USER=root
      - DB_PASSWORD=f48dfe2976bd878d
      - DB_PORT=3306
    networks:
      - rede_geral

networks:
  rede_geral:
    external: true
